version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=C1bDigital123

  phonebook.api:
    image: ${DOCKER_REGISTRY-}phonebook
    build:
      context: .
      dockerfile: PhoneBook.API/Dockerfile
    depends_on:
      - db
