version: '3.4'

networks:
  phonebook-app:
    driver: bridge

services:
  db:
    environment:
      POSTGRES_DB: phonebookdb
      POSTGRES_PASSWORD: dbuserpwd123
      POSTGRES_USER: dbuser
    image: postgres:latest
    networks:
      - phonebook-app
    restart: always
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - db_volume:/var/lib/postgresql/data

  phonebook.api:
    image: phonebookapi
    build:
      context: .
      dockerfile: PhoneBook.API/Dockerfile
    depends_on:
        - "db"
    environment:
        DB_CONNECTION_STRING: host=db;port=5432;database=phonebookdb;username=dbuser;password=dbuserpwd123
    networks:
      - phonebook-app  
    ports:
    - "8000:80"

  phonebook.ui:
    image: phonebookui
    build:
      context: .
      dockerfile: PhoneBook.UI/phonebookui/Dockerfile
    depends_on:
        - "phonebook.api"
    networks:
      - phonebook-app  
    ports:
    - "9800:8080"
volumes:
  db_volume:


